# Generated by Django 3.1.7 on 2021-03-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='I am a person', max_length=100),
        ),
    ]
